apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.client.name}}
  labels:
    app.kubernetes.io/instance: {{.Values.nomeModulo}}
    chart: "{{ .Values.nomeModulo }}-{{ .Chart.Version}}"
    release: {{.Values.nomeModulo}}
    heritage: Helm
    app: {{.Values.client.name}}
    version: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{.Values.nomeModulo}}
      app: {{.Values.client.name}}
      version: "1"
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{.Values.nomeModulo}}
        app: {{.Values.client.name}}
        version: "1"
    spec:
      volumes:
        - name: nginx-config-default
          configMap:
            name: {{.Values.client.name}}
      containers:
        - name: {{.Values.client.name}}
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: nginx-config-default
              subPath: default.conf
          resources:
            limits:
              cpu: 1000m
              memory: 768Mi
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - name: http
              containerPort: {{.Values.client.ports.port}}
      imagePullSecrets:
        - name: ancine-registry
