apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-2"
  labels:
    app.kubernetes.io/instance: {{.Values.nomeModulo}}
    chart: "{{ .Values.nomeModulo }}-{{ .Chart.Version}}"
    release: {{.Values.nomeModulo}}
    heritage: Helm
  name: {{.Values.nomeModulo}}-role-config
  labels:
    {{- include " dsgov-angular-components.labels" . | nindent 4 }}
{{ include " dsgov-angular-components.namespace" . | indent 2 }}
rules:
- apiGroups: ['']
  resources: ['configmaps','pods']
  verbs:     ['get','watch','list']
