apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.client.name}}
  labels:
    app.kubernetes.io/instance: {{.Values.nomeModulo}}
    chart: "{{ .Values.nomeModulo }}-{{ .Chart.Version}}"
    release: {{.Values.nomeModulo}}
    heritage: Helm
    app: {{.Values.client.name}}
    application-config: "true"
data:
  default.conf: |-
    server {
      listen 80 default_server;
      listen [::]:80 default_server ipv6only=on;
      root /usr/share/nginx/html;
      index index.html index.htm;
      server_name localhost;
      location / {
        try_files $uri $uri/ =404;
      }
    }
