apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{.Values.client.name}}
spec:
  host: {{.Values.client.name}}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
    - name: main
      labels:
        app.kubernetes.io/instance: {{.Values.nomeModulo}}
        app: {{.Values.client.name}}
        version: "1"
